package com.tlibrary.dao;

import com.tlibrary.model.Multiplechoice;
import com.tlibrary.model.MultiplechoiceWithBLOBs;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

@Component
@Mapper
public interface MultiplechoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multiplechoice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multiplechoice
     *
     * @mbg.generated
     */
    int insert(MultiplechoiceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multiplechoice
     *
     * @mbg.generated
     */
    int insertSelective(MultiplechoiceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multiplechoice
     *
     * @mbg.generated
     */
    MultiplechoiceWithBLOBs selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multiplechoice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(MultiplechoiceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multiplechoice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeyWithBLOBs(MultiplechoiceWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multiplechoice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Multiplechoice record);
}