package com.tlibrary.dao;

import com.tlibrary.model.Multiplechoice;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Component
@Mapper
public interface MultiplechoiceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multiplechoice
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multiplechoice
     *
     * @mbg.generated
     */
    int insert(Multiplechoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multiplechoice
     *
     * @mbg.generated
     */
    int insertSelective(Multiplechoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multiplechoice
     *
     * @mbg.generated
     */
    Multiplechoice selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multiplechoice
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(Multiplechoice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table multiplechoice
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(Multiplechoice record);
}