package com.tlibrary.model;

public class Multiplechoice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiplechoice.ID
     *
     * @mbg.generated
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiplechoice.Title
     *
     * @mbg.generated
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiplechoice.A
     *
     * @mbg.generated
     */
    private String a;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiplechoice.B
     *
     * @mbg.generated
     */
    private String b;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiplechoice.C
     *
     * @mbg.generated
     */
    private String c;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiplechoice.D
     *
     * @mbg.generated
     */
    private String d;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiplechoice.E
     *
     * @mbg.generated
     */
    private String e;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiplechoice.F
     *
     * @mbg.generated
     */
    private String f;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiplechoice.Answer
     *
     * @mbg.generated
     */
    private String answer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiplechoice.ID
     *
     * @return the value of multiplechoice.ID
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiplechoice.ID
     *
     * @param id the value for multiplechoice.ID
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiplechoice.Title
     *
     * @return the value of multiplechoice.Title
     *
     * @mbg.generated
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiplechoice.Title
     *
     * @param title the value for multiplechoice.Title
     *
     * @mbg.generated
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiplechoice.A
     *
     * @return the value of multiplechoice.A
     *
     * @mbg.generated
     */
    public String getA() {
        return a;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiplechoice.A
     *
     * @param a the value for multiplechoice.A
     *
     * @mbg.generated
     */
    public void setA(String a) {
        this.a = a == null ? null : a.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiplechoice.B
     *
     * @return the value of multiplechoice.B
     *
     * @mbg.generated
     */
    public String getB() {
        return b;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiplechoice.B
     *
     * @param b the value for multiplechoice.B
     *
     * @mbg.generated
     */
    public void setB(String b) {
        this.b = b == null ? null : b.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiplechoice.C
     *
     * @return the value of multiplechoice.C
     *
     * @mbg.generated
     */
    public String getC() {
        return c;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiplechoice.C
     *
     * @param c the value for multiplechoice.C
     *
     * @mbg.generated
     */
    public void setC(String c) {
        this.c = c == null ? null : c.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiplechoice.D
     *
     * @return the value of multiplechoice.D
     *
     * @mbg.generated
     */
    public String getD() {
        return d;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiplechoice.D
     *
     * @param d the value for multiplechoice.D
     *
     * @mbg.generated
     */
    public void setD(String d) {
        this.d = d == null ? null : d.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiplechoice.E
     *
     * @return the value of multiplechoice.E
     *
     * @mbg.generated
     */
    public String getE() {
        return e;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiplechoice.E
     *
     * @param e the value for multiplechoice.E
     *
     * @mbg.generated
     */
    public void setE(String e) {
        this.e = e == null ? null : e.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiplechoice.F
     *
     * @return the value of multiplechoice.F
     *
     * @mbg.generated
     */
    public String getF() {
        return f;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiplechoice.F
     *
     * @param f the value for multiplechoice.F
     *
     * @mbg.generated
     */
    public void setF(String f) {
        this.f = f == null ? null : f.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiplechoice.Answer
     *
     * @return the value of multiplechoice.Answer
     *
     * @mbg.generated
     */
    public String getAnswer() {
        return answer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiplechoice.Answer
     *
     * @param answer the value for multiplechoice.Answer
     *
     * @mbg.generated
     */
    public void setAnswer(String answer) {
        this.answer = answer == null ? null : answer.trim();
    }
}