package com.tlibrary.model;

public class MultiplechoiceWithBLOBs extends Multiplechoice {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiplechoice.picA
     *
     * @mbg.generated
     */
    private byte[] pica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiplechoice.picB
     *
     * @mbg.generated
     */
    private byte[] picb;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiplechoice.picC
     *
     * @mbg.generated
     */
    private byte[] picc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiplechoice.picD
     *
     * @mbg.generated
     */
    private byte[] picd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiplechoice.picE
     *
     * @mbg.generated
     */
    private byte[] pice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column multiplechoice.picF
     *
     * @mbg.generated
     */
    private byte[] picf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiplechoice.picA
     *
     * @return the value of multiplechoice.picA
     *
     * @mbg.generated
     */
    public byte[] getPica() {
        return pica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiplechoice.picA
     *
     * @param pica the value for multiplechoice.picA
     *
     * @mbg.generated
     */
    public void setPica(byte[] pica) {
        this.pica = pica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiplechoice.picB
     *
     * @return the value of multiplechoice.picB
     *
     * @mbg.generated
     */
    public byte[] getPicb() {
        return picb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiplechoice.picB
     *
     * @param picb the value for multiplechoice.picB
     *
     * @mbg.generated
     */
    public void setPicb(byte[] picb) {
        this.picb = picb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiplechoice.picC
     *
     * @return the value of multiplechoice.picC
     *
     * @mbg.generated
     */
    public byte[] getPicc() {
        return picc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiplechoice.picC
     *
     * @param picc the value for multiplechoice.picC
     *
     * @mbg.generated
     */
    public void setPicc(byte[] picc) {
        this.picc = picc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiplechoice.picD
     *
     * @return the value of multiplechoice.picD
     *
     * @mbg.generated
     */
    public byte[] getPicd() {
        return picd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiplechoice.picD
     *
     * @param picd the value for multiplechoice.picD
     *
     * @mbg.generated
     */
    public void setPicd(byte[] picd) {
        this.picd = picd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiplechoice.picE
     *
     * @return the value of multiplechoice.picE
     *
     * @mbg.generated
     */
    public byte[] getPice() {
        return pice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiplechoice.picE
     *
     * @param pice the value for multiplechoice.picE
     *
     * @mbg.generated
     */
    public void setPice(byte[] pice) {
        this.pice = pice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column multiplechoice.picF
     *
     * @return the value of multiplechoice.picF
     *
     * @mbg.generated
     */
    public byte[] getPicf() {
        return picf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column multiplechoice.picF
     *
     * @param picf the value for multiplechoice.picF
     *
     * @mbg.generated
     */
    public void setPicf(byte[] picf) {
        this.picf = picf;
    }
}